export type Place = {
  id: string;
  name: string;
  type: "food" | "nature" | "culture";
  location: { lat: number; lng: number };
  openingHours?: string;
  tags?: string[];
  imageUrl?: string;
};

export const northFunPlaces: Place[] = [
  {
    id: "n01",
    name: "貓空纜車",
    type: "nature",
    location: { lat: 24.9666, lng: 121.5794 },
    openingHours: "09:00–21:00",
    tags: ["纜車", "茶園", "夜景"],
    imageUrl: "https://example.com/images/maokong-gondola.jpg",
  },
  {
    id: "n02",
    name: "信義香堤廣場滑輪場",
    type: "culture",
    location: { lat: 25.0336, lng: 121.5646 },
    openingHours: "08:00–22:00",
    tags: ["滑板", "街頭文化", "戶外"],
    imageUrl: "https://example.com/images/xinyi-skatepark.jpg",
  },
  {
    id: "n03",
    name: "台北101觀景台",
    type: "culture",
    location: { lat: 25.033, lng: 121.5623 },
    openingHours: "11:00–21:00",
    tags: ["高空景觀", "城市夜景", "拍照"],
    imageUrl: "https://example.com/images/taipei101-observatory.jpg",
  },
  {
    id: "n04",
    name: "淡水租自行車河濱騎行",
    type: "nature",
    location: { lat: 25.1688, lng: 121.4446 },
    openingHours: "09:00–18:00",
    tags: ["騎車", "夕陽", "親水"],
    imageUrl: "https://example.com/images/tamsui-bike.jpg",
  },
  {
    id: "n05",
    name: "十分放天燈",
    type: "culture",
    location: { lat: 25.0247, lng: 121.7742 },
    openingHours: "09:00–20:00",
    tags: ["祈福", "老街", "拍照"],
    imageUrl: "https://example.com/images/shifen-sky-lantern.jpg",
  },
  {
    id: "n06",
    name: "九份山城夜遊",
    type: "culture",
    location: { lat: 25.1101, lng: 121.8445 },
    openingHours: "全天開放",
    tags: ["懷舊", "夜景", "小吃"],
    imageUrl: "https://example.com/images/jiufen-night.jpg",
  },
  {
    id: "n07",
    name: "金瓜石地質公園",
    type: "nature",
    location: { lat: 25.1214, lng: 121.8535 },
    openingHours: "09:00–17:00",
    tags: ["山景", "地質奇觀", "健行"],
    imageUrl: "https://example.com/images/jinguashi-geo.jpg",
  },
  {
    id: "n08",
    name: "基隆潮境智能海洋館",
    type: "culture",
    location: { lat: 25.1355, lng: 121.7796 },
    openingHours: "09:00–17:00",
    tags: ["海洋教育", "互動展", "親子"],
    imageUrl: "https://example.com/images/chaojing-ocean.jpg",
  },
  {
    id: "n09",
    name: "陽明山泡溫泉體驗",
    type: "nature",
    location: { lat: 25.162, lng: 121.52 },
    openingHours: "10:00–22:00",
    tags: ["溫泉", "放鬆", "冬季推薦"],
    imageUrl: "https://example.com/images/yangmingshan-onsen.jpg",
  },
  {
    id: "n10",
    name: "台北松山文創園區手作市集",
    type: "culture",
    location: { lat: 25.0445, lng: 121.5622 },
    openingHours: "11:00–19:00",
    tags: ["文創", "手作", "週末市集"],
    imageUrl: "https://example.com/images/songshan-market.jpg",
  },
  {
    id: "n11",
    name: "新北歡樂耶誕城（季節限定）",
    type: "culture",
    location: { lat: 25.0124, lng: 121.4636 },
    openingHours: "17:00–22:00",
    tags: ["燈會", "表演", "冬季活動"],
    imageUrl: "https://example.com/images/christmasland.jpg",
  },
  {
    id: "n12",
    name: "桃園Xpark 都會水族館",
    type: "culture",
    location: { lat: 25.0375, lng: 121.5645 },
    openingHours: "10:00–20:00",
    tags: ["水母", "沉浸式", "拍照聖地"],
    imageUrl: "https://example.com/images/xpark.jpg",
  },
  {
    id: "n13",
    name: "石門洞海蝕奇景",
    type: "nature",
    location: { lat: 25.2896, lng: 121.5683 },
    openingHours: "全天開放",
    tags: ["海蝕", "奇岩怪石", "打卡景點"],
    imageUrl: "https://example.com/images/shimen-cave.jpg",
  },
  {
    id: "n14",
    name: "新竹青草湖立槳體驗（SUP）",
    type: "nature",
    location: { lat: 24.8001, lng: 120.9645 },
    openingHours: "08:00–17:00",
    tags: ["水上活動", "立槳", "戶外運動"],
    imageUrl: "https://example.com/images/qingcao-sup.jpg",
  },
  {
    id: "n15",
    name: "桃園大溪老街豆干DIY",
    type: "food",
    location: { lat: 24.8836, lng: 121.2866 },
    openingHours: "10:00–18:00",
    tags: ["豆干DIY", "老街", "伴手禮"],
    imageUrl: "https://example.com/images/daxi-diy.jpg",
  },
];
