export type Place = {
  id: string;
  name: string;
  type: "food" | "nature" | "culture";
  city: string;
  location: { lat: number; lng: number };
  openingHours?: string;
  duration?: number; // 建議停留時間 (小時)
  suitableFor?: string[];
  tags?: string[];
  imageUrl?: string;
  description?: string;
  slogan?: string;
  isOutdoor: boolean;
};

export const northFunPlaces: Place[] = [
  {
    id: "n01",
    name: "貓空纜車",
    type: "nature",
    city: "台北市",
    location: { lat: 24.9666, lng: 121.5794 },
    openingHours: "09:00–21:00",
    duration: 2,
    suitableFor: ["情侶", "家庭", "親子"],
    tags: ["纜車", "茶園", "夜景"],
    imageUrl: "https://example.com/images/maokong-gondola.jpg",
    description: "搭乘纜車俯瞰台北茶園風光",
    isOutdoor: false,
    slogan: "貓空纜車，茶香四溢的空中之旅",
  },
  {
    id: "n02",
    name: "信義香堤廣場滑輪場",
    type: "culture",
    city: "台北市",
    location: { lat: 25.0336, lng: 121.5646 },
    openingHours: "08:00–22:00",
    duration: 1.5,
    suitableFor: ["年輕族群", "親子"],
    tags: ["滑板", "街頭文化", "戶外"],
    imageUrl: "https://example.com/images/xinyi-skatepark.jpg",
    description: "體驗信義區滑板文化",
    isOutdoor: false,
    slogan: "信義香堤，滑板愛好者的天堂",
  },
  {
    id: "n03",
    name: "台北101觀景台",
    type: "culture",
    city: "台北市",
    location: { lat: 25.033, lng: 121.5623 },
    openingHours: "11:00–21:00",
    duration: 1.5,
    suitableFor: ["情侶", "外國旅客"],
    tags: ["高空景觀", "城市夜景", "拍照"],
    imageUrl: "https://example.com/images/taipei101-observatory.jpg",
    description: "360度欣賞台北市景",
    isOutdoor: false,
    slogan: "台北101，城市的心跳，享受城市美景和購物體驗",
  },
  {
    id: "n04",
    name: "淡水租自行車河濱騎行",
    type: "nature",
    city: "新北市",
    location: { lat: 25.1688, lng: 121.4446 },
    openingHours: "09:00–18:00",
    duration: 2,
    suitableFor: ["情侶", "朋友", "家庭"],
    tags: ["騎車", "夕陽", "親水"],
    imageUrl: "https://example.com/images/tamsui-bike.jpg",
    description: "沿河騎行欣賞夕陽景色",
    isOutdoor: false,
    slogan: "淡水河畔，騎行夕陽下的浪漫",
  },
  {
    id: "n05",
    name: "十分放天燈",
    type: "culture",
    city: "新北市",
    location: { lat: 25.0247, lng: 121.7742 },
    openingHours: "09:00–20:00",
    duration: 1.5,
    suitableFor: ["情侶", "朋友"],
    tags: ["祈福", "老街", "拍照"],
    imageUrl: "https://example.com/images/shifen-sky-lantern.jpg",
    description: "寫願望放飛天燈祈福",
    isOutdoor: false,
    slogan: "十分天燈，放飛願望的浪漫時刻",
  },
  {
    id: "n06",
    name: "九份山城夜遊",
    type: "culture",
    city: "新北市",
    location: { lat: 25.1101, lng: 121.8445 },
    openingHours: "全天開放",
    duration: 2,
    suitableFor: ["情侶", "親子", "文青"],
    tags: ["懷舊", "夜景", "小吃"],
    imageUrl: "https://example.com/images/jiufen-night.jpg",
    description: "走訪山城夜景與老街",
    isOutdoor: false,
    slogan: "九份山城，懷舊夜遊的浪漫之旅",
  },
  {
    id: "n07",
    name: "金瓜石地質公園",
    type: "nature",
    city: "新北市",
    location: { lat: 25.1214, lng: 121.8535 },
    openingHours: "09:00–17:00",
    duration: 1.5,
    suitableFor: ["戶外愛好者", "學生"],
    tags: ["山景", "地質奇觀", "健行"],
    imageUrl: "https://example.com/images/jinguashi-geo.jpg",
    description: "觀賞奇岩地貌與山海",
    isOutdoor: false,
    slogan: "金瓜石地質公園，探索自然的奇妙之旅",
  },
  {
    id: "n08",
    name: "基隆潮境智能海洋館",
    type: "culture",
    city: "基隆市",
    location: { lat: 25.1355, lng: 121.7796 },
    openingHours: "09:00–17:00",
    duration: 1.5,
    suitableFor: ["親子", "教育導向"],
    tags: ["海洋教育", "互動展", "親子"],
    imageUrl: "https://example.com/images/chaojing-ocean.jpg",
    description: "互動展覽體驗海洋知識",
    isOutdoor: false,
    slogan: "基隆潮境，智能海洋館帶你探索海洋奧秘",
  },
  {
    id: "n09",
    name: "陽明山泡溫泉體驗",
    type: "nature",
    city: "台北市",
    location: { lat: 25.162, lng: 121.52 },
    openingHours: "10:00–22:00",
    duration: 2,
    suitableFor: ["長輩", "情侶", "家庭"],
    tags: ["溫泉", "放鬆", "冬季推薦"],
    imageUrl: "https://example.com/images/yangmingshan-onsen.jpg",
    description: "溫泉療癒放鬆身心",
    isOutdoor: false,
    slogan: "陽明山溫泉，放鬆身心的自然療癒",
  },
  {
    id: "n10",
    name: "台北松山文創園區手作市集",
    type: "culture",
    city: "台北市",
    location: { lat: 25.0445, lng: 121.5622 },
    openingHours: "11:00–19:00",
    duration: 1.5,
    suitableFor: ["文青", "情侶", "週末遊客"],
    tags: ["文創", "手作", "週末市集"],
    imageUrl: "https://example.com/images/songshan-market.jpg",
    description: "週末手作市集與藝文展",
    isOutdoor: false,
    slogan: "松山文創，手作市集的藝術氛圍",
  },
  {
    id: "n11",
    name: "新北歡樂耶誕城（季節限定）",
    type: "culture",
    city: "新北市",
    location: { lat: 25.0124, lng: 121.4636 },
    openingHours: "17:00–22:00",
    duration: 2,
    suitableFor: ["親子", "情侶", "冬季旅客"],
    tags: ["燈會", "表演", "冬季活動"],
    imageUrl: "https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=400&h=250&fit=crop",
    description: "冬季限定燈光音樂饗宴",
    isOutdoor: false,
    slogan: "新北歡樂耶誕城，冬季浪漫燈光秀",
  },
  {
    id: "n12",
    name: "桃園Xpark 都會水族館",
    type: "culture",
    city: "桃園市",
    location: { lat: 25.0375, lng: 121.5645 },
    openingHours: "10:00–20:00",
    duration: 2,
    suitableFor: ["情侶", "家庭", "拍照愛好者"],
    tags: ["水母", "沉浸式", "拍照聖地"],
    imageUrl: "https://example.com/images/xpark.jpg",
    description: "沉浸式水族館拍照勝地",
    isOutdoor: false,
    slogan: "桃園Xpark，水族館的奇幻世界",
  },
  {
    id: "n13",
    name: "石門洞海蝕奇景",
    type: "nature",
    city: "新北市",
    location: { lat: 25.2896, lng: 121.5683 },
    openingHours: "全天開放",
    duration: 1,
    suitableFor: ["朋友", "攝影師"],
    tags: ["海蝕", "奇岩怪石", "打卡景點"],
    imageUrl: "https://example.com/images/shimen-cave.jpg",
    description: "海風雕刻出自然奇景",
    isOutdoor: false,
    slogan: "石門洞，海風雕刻的自然奇景",
  },
  {
    id: "n14",
    name: "新竹青草湖立槳體驗（SUP）",
    type: "nature",
    city: "新竹市",
    location: { lat: 24.8001, lng: 120.9645 },
    openingHours: "08:00–17:00",
    duration: 2,
    suitableFor: ["運動族群", "朋友", "水上活動愛好者"],
    tags: ["水上活動", "立槳", "戶外運動"],
    imageUrl: "https://example.com/images/qingcao-sup.jpg",
    description: "體驗湖上立槳划行樂趣",
    isOutdoor: false,
    slogan: "青草湖立槳，水上運動的樂趣與挑戰",
  },
  {
    id: "n15",
    name: "桃園大溪老街豆干DIY",
    type: "food",
    city: "桃園市",
    location: { lat: 24.8836, lng: 121.2866 },
    openingHours: "10:00–18:00",
    duration: 1.5,
    suitableFor: ["親子", "朋友", "文青"],
    tags: ["豆干DIY", "老街", "伴手禮"],
    imageUrl: "https://example.com/images/daxi-diy.jpg",
    description: "手作豆干體驗在老街",
    isOutdoor: false,
    slogan: "大溪老街，手作豆干的美味體驗",
  },
  {
    id: "n16",
    name: "板橋林家花園",
    type: "culture",
    city: "新北市",
    location: { lat: 25.0132, lng: 121.4637 },
    openingHours: "09:00–17:00",
    duration: 1.5,
    suitableFor: ["文青", "家庭", "攝影師"],
    tags: ["古蹟", "庭園", "拍照景點"],
    imageUrl: "https://example.com/images/banqiao-lin-garden.jpg",
    description: "欣賞古典園林建築之美，體驗清代士紳生活風貌",
    isOutdoor: false,
    slogan: "林家花園，穿越時光的庭園漫步",
  },
  {
    id: "n18",
    name: "府中15動畫故事館",
    type: "culture",
    city: "新北市",
    location: { lat: 25.0078, lng: 121.4597 },
    openingHours: "10:00–18:00",
    duration: 1.5,
    suitableFor: ["親子", "學生", "動畫迷"],
    tags: ["展覽", "互動體驗", "動畫"],
    imageUrl: "https://example.com/images/fuzhong15.jpg",
    description: "探索台灣動畫歷史與創作，適合親子共遊",
    isOutdoor: false,
    slogan: "府中15，走進動畫世界的奇幻之旅",
  },
  {
    id: "n19",
    name: "板橋435藝文特區",
    type: "culture",
    city: "新北市",
    location: { lat: 25.0093, lng: 121.4573 },
    openingHours: "09:00–17:00",
    duration: 2,
    suitableFor: ["文青", "藝術愛好者", "親子"],
    tags: ["藝術展覽", "親子DIY", "假日市集"],
    imageUrl: "https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=400&h=250&fit=crop",
    description: "集合藝術展演、市集與親子活動的文創空間",
    isOutdoor: false,
    slogan: "435藝文，創意與藝術的交匯地",
  },
  {
    id: "n20",
    name: "環狀線板橋站周邊商圈",
    type: "food",
    city: "新北市",
    location: { lat: 25.0138, lng: 121.4648 },
    openingHours: "10:00–22:00",
    duration: 2,
    suitableFor: ["朋友", "情侶", "購物族"],
    tags: ["購物", "美食", "夜生活"],
    imageUrl: "https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=400&h=250&fit=crop",
    description: "集結百貨、餐廳與夜市，是板橋最熱鬧的商圈之一",
    isOutdoor: false,
    slogan: "板橋站生活圈，吃喝玩樂一站搞定",
  },
  {
    id: "n21",
    name: "大遠百 Mega City 板橋",
    type: "food",
    city: "新北市",
    location: { lat: 25.0145, lng: 121.4671 },
    openingHours: "11:00–22:00",
    duration: 2,
    suitableFor: ["朋友", "購物族", "家庭"],
    tags: ["百貨公司", "美食街", "逛街"],
    imageUrl:
      "https://res.cloudinary.com/dwq2ehew4/image/upload/v1752298273/stay-mi/image/2d91e447-ad68-4709-a819-c46e2c42d5f7/11images.jpg",
    description: "集結時尚購物、美食餐廳與娛樂的商場地標",
    slogan: "Mega City，板橋人的生活中心",
    isOutdoor: false,
  },
  {
    id: "n22",
    name: "新北市市民廣場",
    type: "culture",
    city: "新北市",
    location: { lat: 25.0118, lng: 121.4629 },
    openingHours: "全天開放",
    duration: 1,
    suitableFor: ["散步族", "攝影師", "週末遊客"],
    tags: ["廣場", "表演", "裝置藝術"],
    imageUrl:
      "https://res.cloudinary.com/dwq2ehew4/image/upload/v1752297865/stay-mi/image/2d91e447-ad68-4709-a819-c46e2c42d5f7/233832efd057a24c61ae47a9211225e9.jpg",
    description: "市府旁大型公共空間，常有燈飾展與節慶活動",
    slogan: "市民廣場，城市活動的核心舞台",
    isOutdoor: false,
  },
  {
    id: "n23",
    name: "湳雅夜市",
    type: "food",
    city: "新北市",
    location: { lat: 25.0079, lng: 121.4583 },
    openingHours: "17:00–00:00",
    duration: 1.5,
    suitableFor: ["夜貓族", "小吃控", "觀光客"],
    tags: ["夜市", "台灣小吃", "熱鬧"],
    imageUrl:
      "https://res.cloudinary.com/dwq2ehew4/image/upload/v1752298131/stay-mi/image/2d91e447-ad68-4709-a819-c46e2c42d5f7/_logo.jpg",
    description: "在地人推薦的老字號夜市，聚集各式經典小吃",
    slogan: "湳雅夜市，味蕾與人潮的交會點",
    isOutdoor: false,
  },
  {
    id: "n24",
    name: "板橋第一運動場（運動公園）",
    type: "nature",
    city: "新北市",
    location: { lat: 25.0166, lng: 121.4698 },
    openingHours: "06:00–22:00",
    duration: 1.5,
    suitableFor: ["健身族", "親子", "戶外愛好者"],
    tags: ["運動", "操場", "健行"],
    imageUrl:
      "https://res.cloudinary.com/dwq2ehew4/image/upload/v1752298036/stay-mi/image/2d91e447-ad68-4709-a819-c46e2c42d5f7/5040468_1_1.jpg",
    description: "具備綠地與運動設施，是都市中放鬆與活動的好去處",
    slogan: "板橋運動場，跑步呼吸的新北綠洲",
    isOutdoor: false,
  },
  {
    id: "n25",
    name: "435文創區假日市集",
    type: "culture",
    city: "新北市",
    location: { lat: 25.0093, lng: 121.4573 },
    openingHours: "週末限定",
    duration: 1.5,
    suitableFor: ["文青", "家庭", "手作迷"],
    tags: ["市集", "手作", "文創"],
    imageUrl:
      "https://res.cloudinary.com/dwq2ehew4/image/upload/v1752297865/stay-mi/image/2d91e447-ad68-4709-a819-c46e2c42d5f7/233832efd057a24c61ae47a9211225e9.jpg",
    description: "週末限定文創市集，販售設計商品與特色美食",
    slogan: "週末就來 435，遇見創意生活",
    isOutdoor: false,
  },
];
