import {
  Dumbbell,
  Waves,
  ChefHat,
  ParkingSquare,
  MoveVertical,
  Accessibility,
  Briefcase,
  Presentation,
  TreePine,
  Martini,
  Cigarette,
  CreditCard,
  Baby,
  BookOpen,
  Flame,
  Hand,
  Bike,
  Bus,
  Clock,
  PawPrint,
  Luggage,
  Croissant,
  Bell,
  Printer,
  Library,
  PlugZap,
  Wifi,
  Tv,
  AirVent,
  CupSoda,
  Wind,
  ShowerHead,
  Lock,
  PenLine,
  Sofa,
  Sun,
  Shirt,
  AlarmClock,
} from "lucide-react";

export const hotelFacilitiesHot = [
  { value: "健身房", icon: "dumbbell" },
  { value: "游泳池", icon: "Waves" },
  { value: "早餐供應", icon: "croissant" },
  { value: "停車場", icon: "parkingSquare" },
  { value: "自助洗衣", icon: "washer" },
];
export const hotelFacilities: IconConfigItem[] = [
  { value: "健身房", icon: "dumbbell" },

  { value: "餐廳", icon: "chefHat" },

  { value: "停車場", icon: "parkingSquare" },
  { value: "電梯", icon: "moveVertical" },
  { value: "無障礙設施", icon: "accessibility" },
  { value: "商務中心", icon: "briefcase" },
  { value: "會議室", icon: "presentation" },
  { value: "戶外花園", icon: "treePine" },
  { value: "酒吧", icon: "martini" },
  { value: "吸菸區", icon: "cigarette" },
  { value: "ATM", icon: "creditCard" },
  { value: "兒童遊戲區", icon: "baby" },
  { value: "閱覽室", icon: "bookOpen" },
  { value: "桑拿室", icon: "flame" },
  { value: "按摩服務", icon: "hand" },
  { value: "腳踏車租借", icon: "bike" },
  { value: "接駁服務", icon: "bus" },
  { value: "24小時櫃台", icon: "clock" },
  { value: "寵物友善", icon: "pawPrint" },
  { value: "行李寄放", icon: "luggage" },
  { value: "早餐供應", icon: "croissant" },
  { value: "叫醒服務", icon: "bell" },
  { value: "影印/傳真", icon: "printer" },
  { value: "圖書室", icon: "library" },
  { value: "屋頂露台", icon: "sun" },
  { value: "電動車充電站", icon: "plugZap" },
  { value: "洗衣代送", icon: "shirt" },
];
export const allHotelFacilityValues = [
  "健身房",
  "餐廳",
  "停車場",
  "電梯",
  "無障礙設施",
  "商務中心",
  "會議室",
  "戶外花園",
  "酒吧",
  "吸菸區",
  "ATM",
  "兒童遊戲區",
  "閱覽室",
  "桑拿室",
  "按摩服務",
  "腳踏車租借",
  "接駁服務",
  "24小時櫃台",
  "寵物友善",
  "行李寄放",
  "早餐供應",
  "叫醒服務",
  "影印/傳真",
  "圖書室",
  "屋頂露台",
  "電動車充電站",
  "洗衣代送",
];

export const allRoomServiceValues = [
  "WiFi",
  "電視",
  "空調",
  "熱水壺",
  "吹風機",
  "淋浴設備",
  "保險箱",
  "書桌",
  "沙發",
  "陽台",
  "衣櫃",
  "叫醒服務",
];

export const roomServices: IconConfigItem[] = [
  { value: "WiFi", icon: "wifi" },
  { value: "電視", icon: "tv" },
  { value: "空調", icon: "airVent" },

  { value: "熱水壺", icon: "cupSoda" },
  { value: "吹風機", icon: "wind" },

  { value: "淋浴設備", icon: "showerHead" },
  { value: "保險箱", icon: "lock" },
  { value: "書桌", icon: "penLine" },
  { value: "沙發", icon: "sofa" },
  { value: "陽台", icon: "sun" },
  { value: "衣櫃", icon: "shirt" },

  { value: "叫醒服務", icon: "alarmClock" },
];

export const IconMap = {
  dumbbell: Dumbbell,
  swimming: Waves,
  chefHat: ChefHat,

  parkingSquare: ParkingSquare,
  moveVertical: MoveVertical,
  accessibility: Accessibility,
  briefcase: Briefcase,
  presentation: Presentation,
  treePine: TreePine,
  martini: Martini,
  cigarette: Cigarette,
  creditCard: CreditCard,
  baby: Baby,
  bookOpen: BookOpen,

  flame: Flame,
  hand: Hand,
  bike: Bike,
  bus: Bus,
  clock: Clock,
  pawPrint: PawPrint,
  luggage: Luggage,
  croissant: Croissant,
  bell: Bell,
  printer: Printer,
  library: Library,
  sun: Sun,
  plugZap: PlugZap,
  shirt: Shirt,
  wifi: Wifi,
  tv: Tv,
  airVent: AirVent,

  cupSoda: CupSoda,
  wind: Wind,

  showerHead: ShowerHead,
  lock: Lock,
  penLine: PenLine,
  sofa: Sofa,

  alarmClock: AlarmClock,
} as const;

export type IconKey = keyof typeof IconMap;

export type IconConfigItem = {
  value: string;
  icon: IconKey;
};

export const cityOptions = [
  { label: "台北市", value: "台北市", popularity: 100 },
  { label: "新北市", value: "新北市", popularity: 95 },
  { label: "高雄市", value: "高雄市", popularity: 90 },
  { label: "台中市", value: "台中市", popularity: 88 },
  { label: "台南市", value: "台南市", popularity: 85 },
  { label: "桃園市", value: "桃園市", popularity: 83 },
  { label: "宜蘭縣", value: "宜蘭縣", popularity: 80 },
  { label: "花蓮縣", value: "花蓮縣", popularity: 78 },
  { label: "新竹市", value: "新竹市", popularity: 76 },
  { label: "屏東縣", value: "屏東縣", popularity: 74 },
  { label: "嘉義市", value: "嘉義市", popularity: 70 },
  { label: "新竹縣", value: "新竹縣", popularity: 68 },
  { label: "台東縣", value: "台東縣", popularity: 66 },
  { label: "苗栗縣", value: "苗栗縣", popularity: 64 },
  { label: "澎湖縣", value: "澎湖縣", popularity: 62 },
  { label: "彰化縣", value: "彰化縣", popularity: 60 },
  { label: "南投縣", value: "南投縣", popularity: 58 },
  { label: "嘉義縣", value: "嘉義縣", popularity: 56 },
  { label: "雲林縣", value: "雲林縣", popularity: 55 },
  { label: "基隆市", value: "基隆市", popularity: 54 },
  { label: "金門縣", value: "金門縣", popularity: 52 },
  { label: "連江縣", value: "連江縣", popularity: 50 },
];
