import { HotelType } from "./types";

export const sectionHotels: HotelType[] = [
  {
    title: "晨曦旅居",
    room_type: "經典雙人房",
    region: "台北大安區",
    price: 3600,
    sub_price: 2880,
    stars: 4.7,
    imageUrl: "",
  },
  {
    title: "漣島慢旅",
    room_type: "海景陽台房",
    region: "花蓮壽豐",
    price: 4000,
    sub_price: 3100,
    stars: 4.2,
    imageUrl: "",
  },
  {
    title: "木光山宿",
    room_type: "溫泉家庭房",
    region: "南投埔里",
    price: 5200,
    sub_price: 4280,
    stars: 4.6,
    imageUrl: "",
  },
  {
    title: "巷隅行旅",
    room_type: "標準單人房",
    region: "台中西屯區",
    price: 2300,
    sub_price: 1780,
    stars: 4.6,
    imageUrl: "",
  },
  {
    title: "巷隅行旅",
    room_type: "標準單人房",
    region: "台中西屯區",
    price: 2300,
    sub_price: 1780,
    stars: 4.6,
    imageUrl: "",
  },
  {
    title: "巷隅行旅",
    room_type: "標準單人房",
    region: "台中西屯區",
    price: 2300,
    sub_price: 1780,
    stars: 4.6,
    imageUrl: "",
  },
  {
    title: "巷隅行旅",
    room_type: "標準單人房",
    region: "台中西屯區",
    price: 2300,
    sub_price: 1780,
    stars: 4.6,
    imageUrl: "",
  },
  {
    title: "巷隅行旅",
    room_type: "標準單人房",
    region: "台中西屯區",
    price: 2300,
    sub_price: 1780,
    stars: 4.6,
    imageUrl: "",
  },
  {
    title: "巷隅行旅",
    room_type: "標準單人房",
    region: "台中西屯區",
    price: 2300,
    sub_price: 1780,
    stars: 4.6,
    imageUrl: "",
  },
];
